### ISSUE TITLE
Doesn't compile on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by bracklanna** [whitslack/btctool#2]
gcc -v:
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn.

Tried installing gmp.h from MacPorts.
username%  ports install gmp 

Then tried doing "make" -- I got:
3 pages of compiler warnings & errors concluding with:
11 warnings and 12 errors generated.
make: *** [out/x86_64-apple-darwin14.5.0/util.o] Error 1

I'm not a programmer, anyone care to document the procedure and/or update the code so it can compile easily on Mac OS X?

**Comment by whitslack** [comment]
I'll look into it, but it's not stated anywhere that Mac OS X is supported. It may be that I'm using Linux-only features. But I'll look into it. Maybe it's not too hard to work around.

**Comment by bracklanna** [comment]
Sure, I don't expect it to be, but I thought it wouldn't hurt to ask.
If I can be of help in the process -- if you don't have access to an OS X development environment -- let me know. I.e. I can do test builds or try different compiler options at your suggestion etc.
I also understand if you don't have time / inclination to pursue.

**Comment by whitslack** [comment]
I do have a MacBook that I use when I'm away from home, although I mostly use it for SSH'ing into my "real" (Linux) machines. I would like to make btctool work natively on OS X, though.

**Comment by whitslack** [comment]
Works now. Update to the latest commit and compile using G++ 4.9.

```
$ git pull
$ git submodule update
$ make CXX=g++-4.9
```

If you don't have g++-4.9 installed, you can get it with Homebrew:

```
$ brew install homebrew/versions/gcc49
```

**Comment by bracklanna** [comment]
Additional note for anyone following these instructions to compile on Mac OS X:  (10.10.5 was the version I used)

Be sure your installations of 'brew' are up to date:

     $ brew update

Be sure you have XCode 7.1.1 (or later) installed, and that it is selected as the active version:

     $ brew config
     HOMEBREW_VERSION: 0.9.5
<... 7 or 8 lines omitted >

     Xcode: 7.1.1

If you recently updated X-Code and/or have more than one copy of X-Code available on your machine, use

    $ xcode-select --switch /Applications/Xcode.app/
(replace /Applications/Xcode.app/ with the appropriate full path name if your XCode v7.1.1 app is located elsewhere.)

Once that is done everything should compile without any errors.

**Comment by whitslack** [comment]
For what it's worth, I don't have Xcode installed. You don't need it. Just get the command-line developer tools from Apple. Just typing "gcc" or "make" in the Terminal should be enough to trigger a popup dialog box with an "Install" button.

**Comment by bracklanna** [comment]
Ahh, thanks. That may help future visitors.
